#!/bin/bash
# Setlist CMDR -- Font Cache Setup
# Downloads all fonts used by the app and stores them on the Pi.
# Once run, fonts load from the Pi with no internet required at a venue.
# Run once from the setlist-cmdr directory: bash setup-fonts.sh

set -e
FONT_DIR="$(dirname "$(realpath "$0")")/static/fonts"
mkdir -p "$FONT_DIR"
UA="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 Chrome/120.0.0.0 Safari/537.36"

echo ""
echo "======================================"
echo "  Setlist CMDR -- Font Cache Setup"
echo "======================================"
echo ""
echo "Downloading fonts from Google Fonts..."
echo "This requires an internet connection."
echo ""

# Download a Google Fonts CSS and rewrite URLs to local paths
# Args: $1 = family query string, $2 = output prefix
cache_family() {
  local query="$1"
  local prefix="$2"
  local url="https://fonts.googleapis.com/css2?family=${query}&display=swap"
  local css
  css=$(curl -s -A "$UA" "$url")

  if [ -z "$css" ]; then
    echo "  ERROR: Could not fetch $prefix CSS"
    return 1
  fi

  # Extract each woff2 URL, download the file, replace URL in CSS
  while IFS= read -r font_url; do
    [ -z "$font_url" ] && continue
    local hash
    hash=$(echo "$font_url" | md5sum | cut -c1-8)
    local filename="${prefix}-${hash}.woff2"
    local local_path="$FONT_DIR/$filename"
    local serve_path="/static/fonts/$filename"

    if [ ! -f "$local_path" ]; then
      curl -s -L "$font_url" -o "$local_path"
      echo "  Cached: $filename"
    else
      echo "  Already cached: $filename"
    fi

    # Replace the remote URL with the local path in the CSS
    css="${css//$font_url/$serve_path}"
  done < <(echo "$css" | grep -oP 'https://fonts\.gstatic\.com[^)]+' | sort -u)

  echo "$css"
}

# Fetch and cache each family
{
  echo "/* Setlist CMDR -- locally cached fonts */"
  echo "/* Generated by setup-fonts.sh on $(date) */"
  echo ""
  cache_family "Bebas+Neue" "bebas"
  echo ""
  cache_family "DM+Mono:ital,wght@0,300;0,400;0,500" "dm-mono"
  echo ""
  cache_family "DM+Sans:wght@400;500;600;700" "dm-sans"
} > "$FONT_DIR/fonts.css"

echo ""
echo "Done. Font files saved to: static/fonts/"
echo ""
echo "Restart the server to pick up the cached fonts:"
echo "  sudo systemctl restart setlist-cmdr"
echo ""
echo "After restarting, fonts will load from the Pi with no internet needed."
echo ""
