#!/bin/bash
# Setlist CMDR — Raspberry Pi Setup Script
# Run once as your normal user (not root):  bash setup.sh

set -e
echo ""
echo "═══════════════════════════════════════"
echo "  Setlist CMDR — Pi Setup"
echo "═══════════════════════════════════════"
echo ""

# 0. Disable Wi-Fi power saving
#
# Raspberry Pi OS (Bookworm and later) defaults wlan0 power-save to ON.
# This is a known OS-level default, not something this app introduces, but
# it is the single most common cause of a Pi that drops Wi-Fi after a few
# minutes and only recovers with a reboot — exactly the failure mode this
# app's always-on server and (optional) kiosk browser will surface, simply
# because they keep the Pi busier than an idle install. We fix it here so
# every install gets a stable connection regardless of whether anyone hits
# this problem first.
echo "► Disabling Wi-Fi power save (fixes a known Pi OS default that causes"
echo "  Wi-Fi to drop after a few minutes and require a reboot)..."

# `iw` and `ip` (iproute2) are used throughout this section instead of the
# older `iwconfig`/`ifconfig` (net-tools), since net-tools is not guaranteed
# to be installed by default on current Raspberry Pi OS.
if ! command -v iw >/dev/null 2>&1 || ! command -v ip >/dev/null 2>&1; then
    sudo apt-get install -y iw iproute2 -qq || echo "  (could not install iw/iproute2 — continuing without the Wi-Fi fix)"
fi

WIFI_IFACE="$(iw dev 2>/dev/null | awk '$1=="Interface"{print $2; exit}')"

if [ -z "$WIFI_IFACE" ]; then
    echo "  No wireless interface detected — skipping Wi-Fi stability fixes"
    echo "  (this Pi appears to be Ethernet-only)."
    echo ""
else
sudo tee /etc/systemd/system/wifi-powersave-off.service > /dev/null << EOF
[Unit]
Description=Disable Wi-Fi power save (works around Pi OS default that drops Wi-Fi)
After=network.target sys-subsystem-net-devices-${WIFI_IFACE}.device
Wants=network.target

[Service]
Type=oneshot
ExecStart=/sbin/iw dev ${WIFI_IFACE} set power_save off
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
EOF

sudo systemctl daemon-reload
sudo systemctl enable wifi-powersave-off.service
sudo systemctl start wifi-powersave-off.service || true

# Also disable it immediately for the current boot, and via NetworkManager
# if present, since NetworkManager can re-assert its own powersave setting
# independent of `iw` on Bookworm+.
sudo iw dev "$WIFI_IFACE" set power_save off 2>/dev/null || true
if command -v nmcli >/dev/null 2>&1; then
    NM_CONN="$(nmcli -t -f NAME,DEVICE connection show --active 2>/dev/null | awk -F: -v d="$WIFI_IFACE" '$2==d{print $1; exit}')"
    if [ -n "$NM_CONN" ]; then
        sudo nmcli connection modify "$NM_CONN" 802-11-wireless.powersave 2 2>/dev/null || true
    fi
fi

CUR_PS="$(iw dev "$WIFI_IFACE" get power_save 2>/dev/null | awk '{print $NF}')"
echo "  Wi-Fi power save for $WIFI_IFACE: ${CUR_PS:-unknown} (service installed to keep it off on every boot)"
echo ""

# A second, separate known brcmfmac issue on the Pi's integrated Broadcom
# Wi-Fi chip (3/3B+/4) involves the chip locking up under a flood of
# multicast/mDNS traffic ("brcmf_sdio_hostmail: Unknown mailbox data
# content"). The documented workaround is putting the interface into
# promiscuous mode alongside disabling power save. This is unrelated to
# this app's code; we apply it as a second safety net since it's a one-line,
# low-risk mitigation for a real, separately-documented Pi Wi-Fi bug.
sudo tee /etc/systemd/system/wifi-promisc-on.service > /dev/null << EOF
[Unit]
Description=Enable promiscuous mode on ${WIFI_IFACE} (brcmfmac mdns-flood mitigation)
After=network.target wifi-powersave-off.service
Wants=network.target

[Service]
Type=oneshot
ExecStart=/sbin/ip link set ${WIFI_IFACE} promisc on
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
EOF
sudo systemctl daemon-reload
sudo systemctl enable wifi-promisc-on.service
sudo systemctl start wifi-promisc-on.service || true
sudo ip link set "$WIFI_IFACE" promisc on 2>/dev/null || true
echo "  brcmfmac mDNS-flood mitigation applied (promiscuous mode on $WIFI_IFACE)"
echo ""

# Self-healing watchdog: ping the gateway every 2 minutes; if it's
# unreachable for two checks in a row, cycle the interface (down/up) the
# same way the documented manual fix for the open Trixie Wi-Fi-drop bug
# does (raspberrypi/trixie-feedback#25), so a drop recovers on its own
# instead of needing someone to find a keyboard and physically reboot.
echo "► Installing Wi-Fi watchdog (auto-recovers dropped connections)..."
WATCHDOG_SCRIPT="/usr/local/bin/setlist-cmdr-wifi-watchdog.sh"
sudo tee "$WATCHDOG_SCRIPT" > /dev/null << EOF
#!/bin/bash
# Auto-recovers a dropped Wi-Fi connection without needing physical access.
# Generated by setup.sh — do not edit by hand.
IFACE="$WIFI_IFACE"
GATEWAY="\$(ip route | awk '/default/ {print \$3; exit}')"
[ -z "\$GATEWAY" ] && exit 0
if ! ping -c2 -W3 "\$GATEWAY" >/dev/null 2>&1; then
    logger "setlist-cmdr-wifi-watchdog: gateway unreachable, cycling \$IFACE"
    if command -v nmcli >/dev/null 2>&1; then
        CONN="\$(nmcli -t -f NAME,DEVICE connection show --active 2>/dev/null | awk -F: -v d="\$IFACE" '\$2==d{print \$1; exit}')"
        [ -n "\$CONN" ] && nmcli connection down "\$CONN" 2>/dev/null
        sleep 3
        [ -n "\$CONN" ] && nmcli connection up "\$CONN" 2>/dev/null
    else
        ip link set "\$IFACE" down
        sleep 3
        ip link set "\$IFACE" up
    fi
fi
EOF
sudo chmod +x "$WATCHDOG_SCRIPT"

sudo tee /etc/systemd/system/wifi-watchdog.service > /dev/null << EOF
[Unit]
Description=Setlist CMDR Wi-Fi watchdog (one-shot check)

[Service]
Type=oneshot
ExecStart=$WATCHDOG_SCRIPT
EOF

sudo tee /etc/systemd/system/wifi-watchdog.timer > /dev/null << 'EOF'
[Unit]
Description=Run Setlist CMDR Wi-Fi watchdog every 2 minutes

[Timer]
OnBootSec=2min
OnUnitActiveSec=2min
Persistent=true

[Install]
WantedBy=timers.target
EOF

sudo systemctl daemon-reload
sudo systemctl enable wifi-watchdog.timer
sudo systemctl start wifi-watchdog.timer
echo "  Watchdog installed: checks the gateway every 2 minutes and"
echo "  automatically reconnects $WIFI_IFACE if it drops. View its activity"
echo "  with: sudo journalctl -u wifi-watchdog.service -n 50"
echo ""
fi   # end: WIFI_IFACE detected

# 1. System packages
echo "► Installing system packages..."
sudo apt-get update -qq
sudo apt-get install -y python3-pip python3-venv -qq

# 2. Python virtual environment
echo "► Creating Python virtual environment..."
python3 -m venv venv
source venv/bin/activate
pip install --upgrade pip -q
pip install -r requirements.txt -q
# Optional PDF-import support. Prebuilt wheels exist for Pi/Linux, so this
# normally just works; if it ever fails to build, the app still runs without
# PDF import (set -e is suspended for this one line).
pip install "pdfplumber>=0.11" -q || echo "  (PDF import unavailable — pdfplumber failed to install; all other formats still work)"
deactivate

# 3. Systemd service for auto-start
echo "► Installing systemd service..."
SERVICE_DIR=$(pwd)
cat > /tmp/setlist-cmdr.service << EOF
[Unit]
Description=Setlist CMDR Server
After=network.target

[Service]
User=$USER
WorkingDirectory=$SERVICE_DIR
ExecStart=$SERVICE_DIR/venv/bin/uvicorn main:app --host 0.0.0.0 --port 8000
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF

sudo mv /tmp/setlist-cmdr.service /etc/systemd/system/setlist-cmdr.service
sudo systemctl daemon-reload
sudo systemctl enable setlist-cmdr.service
sudo systemctl start setlist-cmdr.service

echo ""
echo "✓ Setlist CMDR is running!"
echo ""
echo "  Leader view  →  http://$(hostname -I | awk '{print $1}'):8000/leader"
echo "  Musician URL →  http://$(hostname -I | awk '{print $1}'):8000/"
echo ""

# 4. Optional: confidence monitor kiosk on this same Pi
#
# For small shows where a second Pi for the monitor isn't worth it, this Pi
# can also boot straight into a fullscreen browser showing /monitor — as long
# as it's running Raspberry Pi OS *with Desktop* (not Lite) and has a screen
# attached. This step is skipped automatically on Lite/headless installs.
echo "─────────────────────────────────────────"
echo "Optional: confidence monitor on this Pi"
echo "─────────────────────────────────────────"
echo "If this Pi has a screen attached (e.g. for a small show with no second"
echo "monitor Pi), it can boot straight into a fullscreen browser showing the"
echo "confidence monitor."
echo ""

SETUP_KIOSK="${SETUP_MONITOR_KIOSK:-}"
if [ -z "$SETUP_KIOSK" ]; then
    if [ -t 0 ]; then
        read -rp "Set up confidence monitor kiosk on this Pi? [y/N] " ans
        case "$ans" in
            [Yy]*) SETUP_KIOSK="yes" ;;
            *)     SETUP_KIOSK="no" ;;
        esac
    else
        SETUP_KIOSK="no"
        echo "  (non-interactive shell — skipping; re-run with"
        echo "   SETUP_MONITOR_KIOSK=yes bash setup.sh to enable)"
    fi
fi

if [ "$SETUP_KIOSK" = "yes" ]; then
    if [ -z "${XDG_CURRENT_DESKTOP:-}" ] && [ ! -d "$HOME/.config/labwc" ] \
       && [ ! -f "$HOME/.config/wayfire.ini" ] && [ ! -d /etc/xdg/lxsession ]; then
        echo "  No desktop environment detected — this looks like Raspberry Pi OS"
        echo "  Lite (headless). The kiosk needs Raspberry Pi OS with Desktop."
        echo "  Skipping kiosk setup; the server is still installed and running."
    else
        echo "► Setting up confidence monitor kiosk..."

        # Find or install a Chromium binary (package name varies by OS version)
        CHROME_BIN=""
        for c in chromium-browser chromium; do
            if command -v "$c" >/dev/null 2>&1; then CHROME_BIN="$c"; break; fi
        done
        if [ -z "$CHROME_BIN" ]; then
            echo "  Installing Chromium..."
            sudo apt-get install -y chromium-browser -qq 2>/dev/null \
                || sudo apt-get install -y chromium -qq
            for c in chromium-browser chromium; do
                if command -v "$c" >/dev/null 2>&1; then CHROME_BIN="$c"; break; fi
            done
        fi

        if [ -z "$CHROME_BIN" ]; then
            echo "  Could not find or install a Chromium browser — skipping kiosk setup."
        else
            # Wait-for-server wrapper so the kiosk doesn't race the systemd
            # service on first boot (uvicorn can take a few seconds to bind).
            KIOSK_SCRIPT="$HOME/.local/bin/setlist-cmdr-monitor-kiosk.sh"
            mkdir -p "$HOME/.local/bin"
            cat > "$KIOSK_SCRIPT" << 'KIOSK_EOF'
#!/bin/bash
# Wait for the Setlist CMDR server, then launch the confidence monitor
# fullscreen. Generated by setup.sh — do not edit by hand.

# Give the server up to 60s to come up after boot
for i in $(seq 1 60); do
    curl -fs http://localhost:8000/monitor >/dev/null 2>&1 && break
    sleep 1
done

KIOSK_EOF
            # Append the chromium line with the detected binary (can't use
            # single-quoted heredoc above because $CHROME_BIN must expand)
            cat >> "$KIOSK_SCRIPT" << EOF
$CHROME_BIN \\
    --kiosk \\
    --noerrdialogs \\
    --disable-infobars \\
    --no-first-run \\
    --password-store=basic \\
    --ozone-platform=wayland \\
    --start-maximized \\
    http://localhost:8000/monitor
EOF
            chmod +x "$KIOSK_SCRIPT"

            # labwc is the default compositor on current Raspberry Pi OS
            # (Bookworm/Trixie). Older LXDE-based images use the XDG autostart
            # directory instead. Install into whichever is present, both if
            # both are.
            INSTALLED_TO=""

            if [ -d "$HOME/.config/labwc" ] || [ -z "${XDG_CURRENT_DESKTOP:-}" ]; then
                mkdir -p "$HOME/.config/labwc"
                AUTOSTART_FILE="$HOME/.config/labwc/autostart"
                touch "$AUTOSTART_FILE"
                if ! grep -qF "$KIOSK_SCRIPT" "$AUTOSTART_FILE" 2>/dev/null; then
                    echo "$KIOSK_SCRIPT" >> "$AUTOSTART_FILE"
                fi
                INSTALLED_TO="$INSTALLED_TO labwc"
            fi

            if [ -d /etc/xdg/lxsession ]; then
                mkdir -p "$HOME/.config/lxsession/LXDE-pi"
                LXAUTOSTART="$HOME/.config/lxsession/LXDE-pi/autostart"
                if [ ! -f "$LXAUTOSTART" ] && [ -f /etc/xdg/lxsession/LXDE-pi/autostart ]; then
                    cp /etc/xdg/lxsession/LXDE-pi/autostart "$LXAUTOSTART"
                fi
                touch "$LXAUTOSTART"
                if ! grep -qF "$KIOSK_SCRIPT" "$LXAUTOSTART" 2>/dev/null; then
                    echo "@$KIOSK_SCRIPT" >> "$LXAUTOSTART"
                fi
                INSTALLED_TO="$INSTALLED_TO LXDE"
            fi

            # XDG autostart .desktop entry — broad fallback that many session
            # managers (including labwc with xdg-autostart enabled) honor.
            mkdir -p "$HOME/.config/autostart"
            cat > "$HOME/.config/autostart/setlist-cmdr-monitor.desktop" << EOF
[Desktop Entry]
Type=Application
Name=Setlist CMDR Monitor
Exec=$KIOSK_SCRIPT
X-GNOME-Autostart-enabled=true
EOF
            INSTALLED_TO="$INSTALLED_TO xdg-autostart"

            echo "  Kiosk script installed: $KIOSK_SCRIPT"
            echo "  Autostart registered for:$INSTALLED_TO"
            echo "  Make sure 'Boot to Desktop' + auto-login are enabled in"
            echo "  raspi-config (System Options → Boot / Auto Login)."
            echo "  Reboot to launch the monitor automatically."
        fi
    fi
fi

echo ""
